### ISSUE TITLE
How to add elements in map html and css?

### ISSUE THREAD

**Issue by BoBkiNN** [JLyne/LiveAtlas#136]
help i need to create a buttons, but where is files?

**Comment by BoBkiNN** [comment]
[heres](http://n18.joinserver.ru:25690/) is site if you need

**Comment by JLyne** [comment]
If you are referring to the logo in the top corner of the example map, those can be added by using dynmap's `logo` components in configuration.txt.

The example map uses the following configuration:
```yaml
# Note: more than one logo component can be defined
- class: org.dynmap.ClientComponent
  type: logo
  text: ""
  logourl: "https://minecraft.rtgame.co.uk/assets/favicons/favicon-32x32.png"
  linkurl: "https://minecraft.rtgame.co.uk/"
  # Valid positions: top-left, top-right, bottom-left, bottom-right
  position: top-left
````
