### ISSUE TITLE
How to add your buttons to the site

### ISSUE THREAD

**Issue by Kostya-An** [JLyne/LiveAtlas#287]
How can I add my buttons to the site?

**Comment by JLyne** [comment]
If you are referring to the logo in the top corner of the example map, those can be added by using dynmap's `logo` components in configuration.txt.

The example map uses the following configuration:
```yaml
# Note: more than one logo component can be defined
- class: org.dynmap.ClientComponent
  type: logo
  text: ""
  logourl: "https://minecraft.rtgame.co.uk/assets/favicons/favicon-32x32.png"
  linkurl: "https://minecraft.rtgame.co.uk/"
  # Valid positions: top-left, top-right, bottom-left, bottom-right
  position: top-left
````
