### ISSUE TITLE
Failed to load server configuration

### ISSUE THREAD

**Issue by winnipeg21** [JLyne/LiveAtlas#317]
Was looking for a discord doesn't seem to be any to going to ask here. Trying to setup multiserver, got live atlas on a VPS and my server on another dedi. Only setting up SMP right now so I don't about the Towny side right I will just copy the help I get. Using apache too. SMP is using the links from dynmap, still using the internal webserver. Towny one is using the default with the dynmap link. Both don't work sadly. here's my config:

```yaml
 servers: {
                towny: {
                    label: 'Towny',
                    dynmap: {
                        configuration: 'https://108.165.178.131:8123/standalone/configuration.php',
                        update: 'https://108.165.178.131:8123/standalone/update.php?world={world}&ts={timestamp}',
                        sendmessage: 'https://108.165.178.131:8123/standalone/sendmessage.php',
                        login: 'https://108.165.178.131:8123/standalone/login.php',
                        register: 'https://108.165.178.131:8123/standalone/register.php',
                        tiles: 'https://108.165.178.131:8123/standalone/tiles.php?tile=',
                        markers: 'https://108.165.178.131:8123/standalone/markers.php?marker='
                    }
                },
                smp: {
                    label: 'SMP',
                    dynmap: {
                        configuration: 'https://108.165.178.131:8124/standalone/dynmap_config.json?_={timestamp}',
                        update: 'https://108.165.178.131:8124/standalone/dynmap_{world}.json?_={timestamp}',
                        sendmessage: 'https://108.165.178.131:8124/standalone/sendmessage.php',
                        login: 'https://108.165.178.131:8124/standalone/login.php',
                        register: 'https://108.165.178.131:8124/standalone/register.php',
                        tiles: 'https://108.165.178.131:8124/tiles/',
                        markers: 'https://108.165.178.131:8124/tiles/'
                    }
                },
            }`
```

site link is https://test.revivalmc.co. Any help would be good!
